[Interface]
PrivateKey = eNbqPkL5lUHXxA9FGFzB8C+ToXiN66RNoMRgfcO1OWU=
Address = 10.8.0.16/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = br1mZn4i5huokFh/wPom38pQ5GnDri440dWvEIshZlE=
PresharedKey = VV/GqqJQZPDHVEdQIH3lgkb5t/doaCNDC2jTG+Yz3gk=
Endpoint = 147.45.169.35:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
